name: scholar_sync
description: A comprehensive student management application for university students and educators.

publish_to: 'none'

version: 1.0.0+1flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  provider: ^6.1.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true